# ===============================
# CONJUNTO RESIDENCIAL - MVP CONFIG
# ===============================

# Server
server.port=8080

# DataSource - PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.iuevxdziwuluqngcqtqo
spring.datasource.password=sixRTk7aybUVJ?&
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SpringDoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.com.conjunto=DEBUG

# JWT
jwt.secret=B13n3st4r$3cr3tK3y!C4mb14M3P0rUn4Cl4v3Tuy4!!2024
jwt.expiration=86400000